version: '3'
services:
    admin:
        image: admin
        container_name: admin-blue
        env_file: ../.env.production
        build:
            context: ../
        restart: always
        environment:
            - PORT=7021
        ports:
            - 7021:7021
        volumes:
            - ../../resource:/app/public/resource
        networks:
            - common
networks:
    common:
        external: true
