version: '3'
services:
    welfaredream:
        image: welfaredream
        container_name: welfaredream-blue
        env_file: ../.env.production
        build:
            context: ../
        restart: always
        environment:
            - PORT=11011
        ports:
            - 11011:11011
        volumes:
            - ../../resource:/app/public/resource
        networks:
            - common
networks:
    common:
        external: true
